CREATE TABLE IF NOT EXISTS ORDERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    status VARCHAR(10) NOT NULL CHECK (status IN ('PENDING', 'PAID')),
    amount DOUBLE
);